export const keywordList = [
  { label: '지구한바퀴 세계여행', isCheck: false, isNew: true },
  { label: '그림･웹툰', isCheck: true, isNew: false },
  { label: '알수록 좋은 경제', isCheck: false, isNew: false },
  { label: 'IT 트렌드', isCheck: false, isNew: false },
  { label: '사진･촬영', isCheck: false, isNew: false },
  { label: '취향저격 영화 리뷰', isCheck: true, isNew: true },
  { label: '오늘은 이런 책', isCheck: false, isNew: true },
  { label: '뮤직 인사이드', isCheck: false, isNew: false },
  { label: '글쓰기 코치', isCheck: true, isNew: false },
  { label: '직장인 현실 조언', isCheck: false, isNew: true },
  { label: '스타트업 경험담', isCheck: false, isNew: false },
  { label: '육아 이야기', isCheck: true, isNew: false },
  { label: '요리･레시피', isCheck: false, isNew: false },
  { label: '건강･운동', isCheck: false, isNew: false },
  { label: '멘탈 관리 심리 탐구', isCheck: false, isNew: true },
  { label: '디자인 스토리', isCheck: false, isNew: false },
  { label: '문화･예술', isCheck: false, isNew: false },
  { label: '건축･설계', isCheck: false, isNew: false },
  { label: '인문학･철학', isCheck: true, isNew: false },
  { label: '쉽게 읽는 역사', isCheck: false, isNew: false },
  { label: '우리집 반려동물', isCheck: true, isNew: true },
  { label: '멋진 캘리그래피', isCheck: false, isNew: false },
  { label: '사랑･이별', isCheck: false, isNew: false },
  { label: '감성 에세이', isCheck: false, isNew: false },
];
