// 임시데이터, 서버에서 데이터 받아오고는 이 파일 삭제
// import { BannerImage } from './types';

// export const data: BannerImage[] = [
//   {
//     id: 1,
//     title: '최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1',
//     authorName: '홍길동',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 9,
//     bookRuntime: 20,
//     bookDescription:
//       '최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1최근 읽은 책 1',
//     bookRecommendation:
//       '농담처럼 가볍게 읽히지만, 한참을 곱씹게 만드는 매력이 있는 짧은 소설들농담처럼 가볍게 읽히지만, 한참을 곱씹게 만드는 매력이 있는 짧은 소설들',
//   },
//   {
//     id: 2,
//     title: '최근 읽은 책 2',
//     authorName: '홍길동2',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 10,
//     bookRuntime: 25,
//     bookDescription: '책 내용 2',
//     bookRecommendation: '깊이 있는 주제와 ',
//   },
//   {
//     id: 3,
//     title: '최근 읽은 책 3',
//     authorName: '홍길동3',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 8,
//     bookRuntime: 18,
//     bookDescription: '책 내용 3',
//     bookRecommendation: '흥미진진한 이야기와 빠른 전개가 인상적인 책입니다.',
//   },
//   {
//     id: 4,
//     title: '최근 읽은 책 4',
//     authorName: '홍길동4',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 12,
//     bookRuntime: 30,
//     bookDescription: '책 내용 4',
//     bookRecommendation: '섬세한 문체와 감동적인 이야기가 마음을 울리는 작품입니다.',
//   },
//   {
//     id: 5,
//     title: '최근 읽은 책 5',
//     authorName: '홍길동5',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 7,
//     bookRuntime: 22,
//     bookDescription: '책 내용 5',
//     bookRecommendation: '흥미로운 설정과 예상치 못한 반전이 매력적인 소설입니다.',
//   },
//   {
//     id: 6,
//     title: '최근 읽은 책 6',
//     authorName: '홍길동6',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 6,
//     bookRuntime: 15,
//     bookDescription: '책 내용 6',
//     bookRecommendation: '매력적인 캐릭터와 현실감 넘치는 이야기가 돋보입니다.',
//   },
//   {
//     id: 7,
//     title: '최근 읽은 책 7',
//     authorName: '홍길동7',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 14,
//     bookRuntime: 28,
//     bookDescription: '책 내용 7',
//     bookRecommendation: '철학적인 주제와 아름다운 문체가 인상적인 작품입니다.',
//   },
//   {
//     id: 8,
//     title: '최근 읽은 책 8',
//     authorName: '홍길동8',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 11,
//     bookRuntime: 24,
//     bookDescription: '책 내용 8',
//     bookRecommendation: '강렬한 서사와 생생한 묘사가 특징인 소설입니다.',
//   },
//   {
//     id: 9,
//     title: '최근 읽은 책 9',
//     authorName: '홍길동9',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 9,
//     bookRuntime: 20,
//     bookDescription: '책 내용 9',
//     bookRecommendation: '감동적인 이야기와 깊은 주제가 마음을 울리는 책입니다.',
//   },
//   {
//     id: 10,
//     title: '최근 읽은 책 10',
//     authorName: '홍길동10',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 10,
//     bookRuntime: 26,
//     bookDescription: '책 내용 10',
//     bookRecommendation: '매력적인 주제와 뛰어난 전개가 인상적인 작품입니다.',
//   },
//   {
//     id: 11,
//     title: '최근 읽은 책 11',
//     authorName: '홍길동11',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 13,
//     bookRuntime: 29,
//     bookDescription: '책 내용 11',
//     bookRecommendation: '흥미로운 플롯과 생동감 있는 캐릭터가 돋보입니다.',
//   },
//   {
//     id: 12,
//     title: '최근 읽은 책 12',
//     authorName: '홍길동12',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 8,
//     bookRuntime: 19,
//     bookDescription: '책 내용 12',
//     bookRecommendation: '섬세한 묘사와 감동적인 서사가 특징인 소설입니다.',
//   },
//   {
//     id: 13,
//     title: '최근 읽은 책 13',
//     authorName: '홍길동13',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 7,
//     bookRuntime: 21,
//     bookDescription: '책 내용 13',
//     bookRecommendation: '심오한 주제와 감동적인 이야기가 인상적인 작품입니다.',
//   },
//   {
//     id: 14,
//     title: '최근 읽은 책 14',
//     authorName: '홍길동14',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 15,
//     bookRuntime: 31,
//     bookDescription: '책 내용 14',
//     bookRecommendation: '강렬한 전개와 생생한 묘사가 돋보이는 소설입니다.',
//   },
//   {
//     id: 15,
//     title: '최근 읽은 책 15',
//     authorName: '홍길동15',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 6,
//     bookRuntime: 14,
//     bookDescription: '책 내용 15',
//     bookRecommendation: '매력적인 캐릭터와 현실감 넘치는 이야기가 특징입니다.',
//   },
//   {
//     id: 16,
//     title: '최근 읽은 책 16',
//     authorName: '홍길동16',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 11,
//     bookRuntime: 27,
//     bookDescription: '책 내용 16',
//     bookRecommendation: '흥미로운 설정과 예상치 못한 반전이 인상적입니다.',
//   },
//   {
//     id: 17,
//     title: '최근 읽은 책 17',
//     authorName: '홍길동17',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 10,
//     bookRuntime: 23,
//     bookDescription: '책 내용 17',
//     bookRecommendation: '섬세한 문체와 감동적인 이야기가 돋보이는 작품입니다.',
//   },
//   {
//     id: 18,
//     title: '최근 읽은 책 18',
//     authorName: '홍길동18',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 12,
//     bookRuntime: 30,
//     bookDescription: '책 내용 18',
//     bookRecommendation: '깊이 있는 주제와 매력적인 캐릭터가 인상적인 소설입니다.',
//   },
//   {
//     id: 19,
//     title: '최근 읽은 책 19',
//     authorName: '홍길동19',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 9,
//     bookRuntime: 20,
//     bookDescription: '책 내용 19',
//     bookRecommendation: '농담처럼 가볍게 읽히지만, 한참을 곱씹게 만드는 매력이 있는 책입니다.',
//   },
//   {
//     id: 20,
//     title: '최근 읽은 책 20',
//     authorName: '홍길동20',
//     bannerImage: 'https://via.placeholder.com/184x256',
//     bookEpisode: 8,
//     bookRuntime: 18,
//     bookDescription: '책 내용 20',
//     bookRecommendation: '흥미진진한 이야기와 빠른 전개가 돋보이는 소설입니다.',
//   },
// ];
